on:
  push:
  pull_request:
    branches: [main]

env:
  CI_py_version: "3.10"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.CI_py_version }}
      - uses: snok/install-poetry@v1
      - run: poetry install
      - run: poetry run pytest